name: 'Tests & Linting'

on:
  push:
    branches: [main]
  pull_request:
    branches: []

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: yarn
      - run: yarn build
      - run: yarn test
      - run: yarn lint
